name: blast-lite
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - matplotlib
  - myst-parser
  - scipy
  - seaborn
  - sphinx-copybutton
  - pydata-sphinx-theme
  - pytables
  - ipykernel
  - nrel-rex
  - pip
  - pip:
    - geopy